import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
// import { Header } from "@/components/header";
// import { FloatingDockDemo } from "@/components/floating-dock-demo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "James Leone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${geistSans.className} antialiased`}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
